version: '3.4'

services:
  fladder:
    image: ghcr.io/donutware/fladder:latest
    ports:
      - 80:80
    environment:
      - BASE_URL=https://server-url #OPTIONAL: Locks the Fladder front-end to a certain jellyfin server
