blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¡ Feature Request"
    url: "https://github.com/DonutWare/Fladder/discussions/new?category=ideas"
    about: "Suggest a new feature or enhancement."
